[build]
  base = "hello_user/frontend"
  publish = "build"
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "hello_user/netlify/functions"

[build.environment]
  NODE_VERSION = "20.14.0"
